### PR TITLE
add other nwc requests

### PR DESCRIPTION
**Pull request by elnosh**
Pardon my mediocre frontend skills. Added `multi_pay_invoice`, `pay_keysend` and `multi_pay_keysend` for me to test adding those nwc commands to mutiny-node :)

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]
good enough for me!

**Comment by benthecarman** [comment]
deployed!

**Comment by benthecarman** [comment]
image

these buttons are huge, maybe @futurepaul can pretty this up

**Comment by elnosh** [comment]
cool, thanks! 

> maybe @futurepaul can pretty this up

that would be great

**Pull request merged**
